export const portfolioItems = [
  {
    slug: "wine-lounge",
    title: "Wine Lounge",
    tags: ["Pure HTML", "NextJs", "Client App"],
    gradient: "var(--gradient-portfolio-1)",
    type: "Landing Page + Web App",
    link: "https://wineslounge.com/",
  },
  {
    slug: "superoh",
    title: "SuperOH",
    tags: ["NextJs", "iGaming", "Frontend"],
    gradient: "var(--gradient-portfolio-2)",
    type: "Platform",
    link: "https://igaming-platform.vercel.app/",
  },
  {
    slug: "cod-auto-pro",
    title: "COD Auto Pro",
    tags: ["Pure HTML", "Corporate", "Services"],
    gradient: "var(--gradient-portfolio-3)",
    type: "Landing Page",
    link: "https://codautopro.com.my/",
  },
  {
    slug: "kepong-honda",
    title: "Kepong Honda",
    tags: ["Pure HTML", "Automotive", "Landing Page"],
    gradient: "var(--gradient-portfolio-4)",
    type: "Landing Page",
    link: "https://keponghonda.com/",
  },
  {
    slug: "hk-fun-casino",
    title: "HK Fun Casino",
    tags: ["Wordpress", "Blog", "Reviews"],
    gradient: "var(--gradient-portfolio-5)",
    type: "Blog",
    link: "https://hkfuncasinoonline.com/",
  },
  {
    slug: "hk-trusted-groups",
    title: "HK Trusted Groups",
    tags: ["Review Platform", "Referral", "Web"],
    gradient: "var(--gradient-portfolio-6)",
    type: "Landing Page",
    link: "https://hktrustedgroups.com/",
  },
];
